# ############################################################################## #
# you do not have to specify everything, pick and choose the options you need only
# ############################################################################## #

[app::general]
# by default the emu will report a `non-beta` branch when the game calls `Steam_Apps::GetCurrentBetaName()`
# 1=make the game/app think we're playing on a beta branch
# default=0
is_beta_branch=0
# the name of the current branch, this must also exist in branches.json
# otherwise will be ignored by the emu and the default 'public' branch will be used
# default=public
branch_name=public

[app::dlcs]
# 1=report all DLCs as unlocked
# 0=report only the DLCs mentioned
# some games check for "hidden" DLCs, hence this should be set to 1 in that case
# but other games detect emus by querying for a fake/bad DLC, hence this should be set to 0 in that case
# default=1
unlock_all=0
# 1=report appid 4294967295 as a valid DLC
# 0=do not report appid 4294967295 as a valid DLC
# some rare games may depend on appid 4294967295 as a valid DLC to unlock
# this option is to support this behavior without breaking major games
# default=0
unlock_uint32max=0
# format: ID=name
1234=DLCNAME
56789=This is another example DLC name

[app::paths]
# some rare games might need to be provided one or more paths to appids
# for example the path to where a DLC is installed
# this sets the paths returned by the Steam_Apps::GetAppInstallDir function
556760=../DLCRoot0
1234=./folder_where_steam_api_is
3456=../folder_one_level_above_where_steam_api_is
5678=../../folder_two_levels_above_where_steam_api_is
# however some other games might expect this function to return empty paths to properly load DLCs
# you can deliberately set the path to be empty to specify this behavior like lines below
1337=
